### ISSUE TITLE
It crashes.

### ISSUE THREAD

**Issue by MarkusHaas2002** [iamvinny/instasniper#2]
It always crasches but theres no error output
```
[---------------------------------------]
[ Instagram BruteForce v1.1  By: Vinny! ]
[---------------------------------------]

[!] Password and Proxy list loaded succesfully!

[!] 101 passwords have been loaded.

[!] Starting the attack...
```

**Comment by iamvinny** [comment]
What OS are you using? Do you have PHP Curl installed?

**Comment by MarkusHaas2002** [comment]
kali linux and yes

**Comment by iamvinny** [comment]
Ok, try enabling the logs, comment out this line.

> // error_reporting(0);

**Comment by MarkusHaas2002** [comment]
It´s already uncommented

**Comment by iamvinny** [comment]
ok, replace the `0` with `E_ALL`

Like this:

`error_reporting(E_ALL);`

save and and try to run the script again..

**Comment by MarkusHaas2002** [comment]
Report:
`PHP Fatal error:  Uncaught Error: Call to undefined function curl_init() in /root/instasniper/script.php:63
Stack trace:
#0 {main}
  thrown in /root/instasniper/script.php on line 63
`

**Comment by iamvinny** [comment]
It seems like you don’t have fuel installed.

Install it with:
`sudo apt-get install php-curl`

And restart apache 
`sudo service apache2 restart`
